---


- name: Deploy gitlab server
  include: "sync_file_and_apply.yml"
  vars:
    filename: "gitlab-server.yml"

- name: Wait Gitlab to be ready
  uri:
    url: http://localhost:8080/api/v4/runners
    method: GET
    return_content: yes
    status_code: 401
    body_format: json
  ignore_errors: yes
  register: result
  until: result.content.find("{\"message\":\"401 Unauthorized\"}") != -1
  retries: 100
  delay: 5
  changed_when: false

- name: Wait Gitlab to be ready
  debug:
    msg: "{{ result.content }}"
