---

- name: Clone always new version to tmp
  shell: rm -rf "{{ repopath}}" ; git clone "{{ main_repo }}" "{{ repopath }}"

- name: Push the code for Local Gitlab
  command: git push --set-upstream http://root:password@localhost:8080/root/flask-with-test.git master
  args:
    chdir: "{{ repopath }}"
