apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-managed

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-managed-sa
  namespace: gitlab-managed

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gitlab-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitlab-rbac
subjects:
- kind: ServiceAccount
  name: gitlab-managed-sa
  namespace: gitlab-managed
roleRef:
  kind: ClusterRole
  name: gitlab-admin
  apiGroup: rbac.authorization.k8s.io
